#created on: 2009-12-02
package chatbot.engine
import chatbot.user.User;
import chatbot.engine.ChatbotEngine;

function boolean pasuje(String value, String pattern )
{
	boolean jest=false;
	String rob=" "+value+" ";
	if (rob.indexOf(" "+pattern+" ")>=0)
	  jest=true;
	 
	return jest;  
}

rule "Przywitaj sie"
	
	when
		$u : User()
		
		eval( 	pasuje($u.getMessage(),"CZESC")||
				pasuje($u.getMessage(),"HEJ")||
				pasuje($u.getMessage(),"SIEMA")||
				pasuje($u.getMessage(),"CZE")||
				pasuje($u.getMessage(),"WITKA")||
				pasuje($u.getMessage(),"YO")||
				pasuje($u.getMessage(),"JO")||
				pasuje($u.getMessage(),"ELO")||
				pasuje($u.getMessage(),"HEJKA")||
				pasuje($u.getMessage(),"HELO")||
				pasuje($u.getMessage(),"HELLO")||
				pasuje($u.getMessage(),"WITAM")||
				pasuje($u.getMessage(),"WITAJ"))
	then 
		
		System.out.println("Oh it works");	
end