#created on: 2009-12-02
package chatbot
import chatbot.user.User;
import chatbot.engine.ChatbotEngine;
import java.util.Random;
import chatbot.helper.Helper;



rule "Przywitaj sie"
	
	when
		$u : User()
		$h : Helper(  )
		
		eval( 	$h.pasuje($u.getMessage(),"CZESC")||
				$h.pasuje($u.getMessage(),"HEJ")||
				$h.pasuje($u.getMessage(),"SIEMA")||
				$h.pasuje($u.getMessage(),"CZE")||
				$h.pasuje($u.getMessage(),"WITKA")||
				$h.pasuje($u.getMessage(),"YO")||
				$h.pasuje($u.getMessage(),"JO")||
				$h.pasuje($u.getMessage(),"ELO")||
				$h.pasuje($u.getMessage(),"HEJKA")||
				$h.pasuje($u.getMessage(),"HELO")||
				$h.pasuje($u.getMessage(),"HELLO")||
				$h.pasuje($u.getMessage(),"WITAM")||
				$h.pasuje($u.getMessage(),"WITAJ"))
	then 
		
		
		switch ($h.randomGen(9)){
		case 1: $u.setMessage( "CZESC");break;
		case 2: $u.setMessage( "HEJ" );break;
		case 3: $u.setMessage( "SIEMA" );break;
		case 4: $u.setMessage( "WITKA" );break;
		case 5: $u.setMessage( "HEJKA" );break;
		case 6: $u.setMessage( "HELLO" );break;
		case 7: $u.setMessage( "WITAM" );break;
		case 8: $u.setMessage( "WITAJ" );break;
		case 9: $u.setMessage( "DZIEN DOBRY" );break;
		default: $u.setMessage("Blad w : CZY JESTES ");break;
		}
		System.out.println($u.getMessage());	
end

