#created on: 2009-12-02
package chatbot
import chatbot.user.User;
import chatbot.engine.ChatbotEngine;
import java.util.Random;
import function chatbot.helper.Helper.pasuje;
import function chatbot.helper.Helper.randomGen;

rule "Monit"
	dialect "mvel" 
	when
		eval(true)
		$u:User()
	then
	#	System.out.println("Czesc men");
		System.out.println("Status: "+$u.status);

		
end

rule "Chatbot sie wita"
	dialect "mvel" 
	when
		$u : User($u.status == User.Status.nieprzywitany)
	then
		System.out.println("Czesc, jesetem Chatbotem, na poczatku przydaloby sie przywitac");	
end

rule "Przywitaj sie"
	
	when
		$u : User($u.status == User.Status.nieprzywitany)
	
		
		eval( 	pasuje($u.getMessage(),"CZESC")||
				pasuje($u.getMessage(),"HEJ")||
				pasuje($u.getMessage(),"SIEMA")||
				pasuje($u.getMessage(),"CZE")||
				pasuje($u.getMessage(),"WITKA")||
				pasuje($u.getMessage(),"YO")||
				pasuje($u.getMessage(),"JO")||
				pasuje($u.getMessage(),"ELO")||
				pasuje($u.getMessage(),"HEJKA")||
				pasuje($u.getMessage(),"HELO")||
				pasuje($u.getMessage(),"HELLO")||
				pasuje($u.getMessage(),"WITAM")||
				pasuje($u.getMessage(),"WITAJ"))
	then 
		
		
		switch (randomGen(9)){
		case 1: $u.setMessage( "CZESC");break;
		case 2: $u.setMessage( "HEJ" );break;
		case 3: $u.setMessage( "SIEMA" );break;
		case 4: $u.setMessage( "WITKA" );break;
		case 5: $u.setMessage( "HEJKA" );break;
		case 6: $u.setMessage( "HELLO" );break;
		case 7: $u.setMessage( "WITAM" );break;
		case 8: $u.setMessage( "WITAJ" );break;
		case 9: $u.setMessage( "DZIEN DOBRY" );break;
		}
		System.out.println($u.getMessage());	
		$u.setStatus(User.Status.przywitany);
		modify($u){}
end

rule "Pozegnaj sie"
	
	when
		$u : User($u.status == User.Status.nieprzywitany)
	
		
		eval( 	pasuje($u.getMessage(),"PAPA")||
				pasuje($u.getMessage(),"ZEGNAJ")||
				pasuje($u.getMessage(),"NARAZIE")||
	then 
		switch (randomGen(3)){
		case 1: $u.setMessage( "PAPA");break;
		case 2: $u.setMessage( "ZEGNAJ" );break;
		case 3: $u.setMessage( "NARAZIE" );break;
		}
		System.out.println($u.getMessage());	
		$u.setStatus(User.Status.pozegnany);
		modify($u){}
end
