#created on: 2009-12-07
package chatbot
import chatbot.User;
import chatbot.Chatbot;

rule "Sledz wulgaryzmy"
no-loop true
	when
		$c : Chatbot()
		$u : User()
	then
		System.out.println(" przeklales: "+$c.getCountVulgarism()+" razy");	
		System.out.println(" Humor Chatbota: " + $c.getNastroj());
		System.out.println(" Humor Usera: " + $u.getNastroj());
		System.out.println(" Przywitanie Usera: " + $u.getPrzywitanie());
		System.out.println(" Stan Usera: " + $c.getStany());
end