#created on: 2009-12-08
package chatbot
import chatbot.user.User;
import chatbot.engine.ChatbotEngine;
import java.util.Random;
import chatbot.helper.Helper;
import function chatbot.helper.Helper.pasuje;
import function chatbot.helper.Helper.randomGen;
import chatbot.chatbot.Chatbot;
global Chatbot chatbot;


rule "Wylap wulgaryzmy"
	salience 100
	when
		$u : User()
	
		
		eval( 	pasuje($u.getMessage(),"JELEN")  ||
				pasuje($u.getMessage(),"MENDA")	||
				pasuje($u.getMessage(),"CWANIAK")	||
				pasuje($u.getMessage(),"DEBIL")	||
				pasuje($u.getMessage(),"MATOL")	||
				pasuje($u.getMessage(),"FRAJER")||
				pasuje($u.getMessage(),"CIOTA")	||
				pasuje($u.getMessage(),"GEJ")
			)
	then 
		
		
		switch (randomGen(8)){
		case 1: $u.setMessage( "UWAZAJ JAK SIE WYRAZASZ");break;
		case 2: $u.setMessage( "TWOJ SPOSOB WYRAZANIA NIE BEDZIE TOLEROWANY" );break;
		case 3: $u.setMessage( "JESTES WULGARNY, MASZ OSTRZEZENIE" );break;
		case 4: $u.setMessage( "JESTES ZLE WYCHOWANY" );break;
		case 5: $u.setMessage( "NIE BEDZIEMY TAK DLUZEJ ROZMAWIAC" );break;
		case 6: $u.setMessage( "NIE PODOBA MI SIE TON TWEGO GLOSU" );break;
		case 7: $u.setMessage( "MASZ OSTATNIA SZANSE" );break;
		case 8: $u.setMessage( "CZY JA BYLEM DLA CIEBIE NIE MILY?" );break;
		default: $u.setMessage("Blad w : CZY JESTES ");break;
		}
		
		modify($u){setCountVulgarism()}
		System.out.println($u.getMessage()+" przeklales "+$u.getCountVulgarism()+" razy");	
end